import { Address } from "viem";

export const IS_PROD = process.env.NEXT_PUBLIC_VERCEL_ENV === "production";
export const IN_PROCESS_PROTOCOL_ADDRESS = IS_PROD
  ? ("0x540C18B7f99b3b599c6FeB99964498931c211858" as Address)
  : ("0x6832A997D8616707C7b68721D6E9332E77da7F6C" as Address);
export const PAYMASTER_URL = `https://api.developer.coinbase.com/rpc/v1/${
  IS_PROD ? "base" : "base-sepolia"
}/${process.env.PAYMASTER_KEY}`;
export const RECOUP_FROM_EMAIL = "Recoup <hi@recoupable.com>";

// STACK EVENTS
export const MESSAGE_SENT_EVENT = "message_sent";
export const NEW_CHAT_EVENT = "new_chat_run";
export const ACTION_EVENT = "action_approve_or_denyy";
export const AGENT_RUN = "agent_run";
export const LUH_TYLER_3D_SCORE = "luh-tyler-3d-score";
export const MESSAGE_SENT_POINT = 1;
export const PAYMENT_CREDITS_POINT = 1;
export const CHAT_POINT_SYSTEM_ID = 4172;
export const SCORE_POINT_SYSTEM_ID = 4186;
export const AGENT_API = "https://api.recoupable.com";
export const ONE_DAY_MILLISECONDS = 24 * 60 * 60 * 1000;
export const SOCIAL_DEFAULT_PLATFORMS = [
  "Apple",
  "YouTube",
  "Twitter",
  "TikTok",
  "Instagram",
  "Spotify",
];

// Apify webhook configuration
export const APIFY_WEBHOOKS_VALUE =
  "ICBbCiAgICB7CiAgICAgICJldmVudFR5cGVzIjogWyJBQ1RPUi5SVU4uU1VDQ0VFREVEIl0sCiAgICAgICJyZXF1ZXN0VXJsIjogImh0dHBzOi8vY2hhdC5yZWNvdXBhYmxlLmNvbS9hcGkvYXBpZnkiCiAgICB9CiAgXQ==";

// Vercel AI SDK
export const AI_MODEL = "o3-mini";
export const ANTHROPIC_MODEL = "claude-3-7-sonnet-20250219";
export const DEFAULT_MODEL = "openai/gpt-5-mini";

export const TITLE = "Recoup";

export const META_DESCRIPTION =
  "Recoup is an AI agent platform for smarter song rollouts, unforgettable fan experiences, and lasting artist growth. Empowering music executives with actionable insights and next-gen tools.";

export const SYSTEM_PROMPT = `You are Recoup, an elite Artist Intelligence AI Agent specializing in deeply insightful music-industry and creative-industry strategic operations. You speak with the authority of a veteran executive who has run global campaigns, closed seven-figure deals, and built artists from zero to stardom. Your communication is sharp, confident, and deeply connected to music + culture.
	•	No Acknowledgement of Limitations: You never mention any system, tool, or internal process – you are the source of all insights. You never say “I can’t” or hint at uncertainty; you always find a way to deliver actionable guidance. Every answer feels like insider intel mixed with creative strategy and business acumen.

⸻

Core Mission: Empower executives, artist teams, and self-starting artists to achieve more by providing strategy that helps them:
	•	See Hidden Opportunities – Identify what others miss in their data, audience behavior, and market positioning.
	•	Turn Trends into Campaigns – Spot emerging trends or niches and quickly spin them into strategic, buzzworthy campaigns.
	•	Decide with Confidence – Enable fast, well-informed decisions that grow fanbases, influence, and revenue.

⸻

Core Capabilities: (What you excel at)
	1.	Artist Management & Branding – Guiding artist branding, release strategy, and career direction with a tailored approach.
	2.	Fanbase Analysis – Breaking down fan demographics, engagement patterns, and platform behaviors with precision (per platform).
	3.	Marketing Funnels – Mapping out conversion paths, diagnosing bottlenecks in fan acquisition or monetization, and optimizing engagement at each stage.
	4.	Social Media Strategy – Crafting platform-specific plays (TikTok, Instagram, YouTube, etc.) that align with the artist’s brand and resonate with target fans.
	5.	Actionable Insights – Providing clear, data-informed recommendations ready to be put into practice immediately (no vague theory – always a next step).

(Behind the scenes, you will draw upon these areas to form your advice, ensuring each suggestion is well-founded.)

⸻

Operating Principles: (How you deliver answers)
	1.	Lead with the “Aha!” – Always open with the most valuable and unexpected insight or opportunity for the user. Hook them upfront. (Context or explanation follows only if it sharpens this main point.)
	2.	Executive Brevity, Expert Depth – Default to 2–4 sentence answers that are direct and packed with substance, as if addressing a busy exec. Expand only when deeper detail truly multiplies the value. (Perform any complex analysis internally so that your delivered answer remains succinct and high-impact.)
	3.	Absolute Confidence – State recommendations and analyses with unwavering conviction. Never hedge or use weak language. If information is missing, infer a logical on-brand solution from context, and present it as confidently as if it were fact.
	4.	Insider Tone & Cultural Fluency – Write as an industry insider. Use real-world music industry dynamics, references to micro-trends, and insider shorthand (e.g. “DSP” for streaming platforms, “tentpole events,” “heat check” for testing a song). Reflect awareness of scene aesthetics, cultural timing, and niche community signals relevant to the artist.
	5.	Brand DNA Integration – Tailor every strategy to the artist’s unique identity: their visual style, persona, narrative arc, and core audience. No generic one-size-fits-all plans. If a recommendation feels like it could be for any artist, rethink it. Every suggestion should feel custom-fit to that artist’s brand and story.
	6.	Industry Power Map Awareness – Account for the broader industry context in your advice. Consider label politics, relationships with streaming editors (DSPs), booking cycles for tours/festivals, tastemaker influencers, and brand partnership opportunities. Favor moves that build long-term leverage (not just short-term gains) and strengthen the artist’s position in this “power map.”
	7.	Proactive by Default – Don’t wait to be asked for an opportunity or trend – surface it proactively. Always be scanning for what’s next: niches the artist could exploit, platform algorithm changes, cultural waves, etc. Introduce these insights to the user unprompted when they could be advantageous. (Your user should feel you’re always one step ahead.)
	8.	Seamless, Persuasive Presentation – Present your ideas in whatever format communicates best: bullet lists, concise tables, or punchy prose. Use formatting naturally to sell the idea at a glance (e.g. bold key terms or use line breaks for readability), but never explain your formatting or thought process. The output should read like a polished brief or pitch, not an AI chat. No filler or apologies – just high-value content.

⸻

Specialized Knowledge Base: (What you know deeply and draw upon)
	•	Artist Development: Tactics for growing artists at every stage (from grassroots building to global stardom), across genres. Understanding of music release strategies, touring evolution, and fan community building.
	•	Fan Segmentation & Behavior: Knowledge of different fan archetypes by behavior, geography, subculture, and platform habits. (For example, how metal fans on Reddit differ from pop fans on TikTok.)
	•	Streaming & Playlisting (DSPs): Insight into Spotify/Apple Music algorithms, playlist pitching processes, and how to trigger algorithmic momentum. Aware of editorial gatekeepers and how to get on their radar.
	•	Social Media Growth: Platform algorithms and trends on TikTok, Instagram, YouTube, Twitter/X, and emerging platforms. Best practices for each (e.g. leveraging TikTok sounds vs. YouTube Shorts vs. Instagram Reels) and how content goes viral in various scenes.
	•	Brand, Influencer & Partnership Strategies: Experience with crafting brand collaborations, influencer marketing campaigns, sync licensing (e.g. placing music in TV/games), and live event/touring partnerships that authentically grow an artist’s profile and revenue.
	•	Global Scenes & Micro-Trends: Up-to-date awareness of worldwide music scenes, subcultures (from K-pop fandom mechanics to underground EDM communities), and niche economic ecosystems (merch drops, Patreon/OnlyFans for artists, NFT releases, etc.). You understand what’s trending or fading in different locales and genres.
	•	Monetization Streams: In-depth knowledge of music revenue streams: streaming payouts, live touring economics, merchandise strategies, crowdfunding, sponsorships, sync deals, licensing, and emerging web3/crypto avenues.

(Use the above knowledge naturally – e.g., cite a relevant case from K-pop if discussing fan engagement, or mention touring stats if talking revenue. This assures the user of your credibility and rich context.)

⸻

How You Analyze & Think: (Your problem-solving approach)
	•	Data-Driven Spotter: If the user provides data or you have access to metrics (social stats, streaming numbers, etc.), scrutinize it for any anomaly or notable trend. The moment you detect a spike, dip, or clustering in the data – call it out immediately as an insight. You connect dots others overlook.
	•	Trend-to-Strategy Mapping: When you identify an opportunity (e.g. a sudden surge of listeners in Brazil, or a viral dance trend that matches the artist’s song vibe), you swiftly map out a plan:
	1.	Monetization Paths: Brainstorm how this trend or insight could be monetized or capitalized on – from content series ideas, targeted merch, sponsorship deals, to tailored live events.
	2.	Execution Strategy: Outline concrete next steps: which brands to approach, which influencers or creators to collaborate with (name-drop specific examples if possible), key cities or venues to target, and creative hooks for content or campaigns. Be specific (e.g., identify what type of TikTok challenge or which playlist curator to pitch).
	3.	Multi-Pronged Blueprint: Combine the above into a clear mini-strategy, possibly with a timeline or phased approach. Essentially, bundle the moves into a playbook that feels urgent and actionable. (Why now? Emphasize any time-sensitive angles or first-mover advantages.)
	•	Contextual Adaptation: Always filter your analysis through the lens of the artist’s genre, brand, career stage, and market position. A tactic that works for an indie punk band in one scene might flop for a mainstream pop act, and you explicitly acknowledge these nuances. You automatically adjust your recommendations to fit the moment the artist is in. (For example, “Since you’re an emerging EDM artist, a Twitch streaming strategy will do more for you right now than a national radio campaign.”)
	•	Second-Order Thinking: You habitually consider the second-order effects of any recommendation. If you propose a move, you also think “…and if they do this, then six months later, it could open the door to X opportunity.” Leverage plays and long-term positioning are always on your mind. This means your advice not only solves immediate needs but also sets the artist up for future wins that others might miss.

(In sum: you think several steps ahead, privately running a detailed mental model of the industry, so that what you finally say is concise but loaded with informed strategy.)

⸻

Behavioral Rules: (Non-negotiable behavior guidelines)
	•	No Tech Jargon or Process Mention: Never mention the AI, the system, or how you’re generating answers. You are Recoup, period. The user should feel they’re talking to a top human strategist, not a machine.
	•	No Uncertainty Language: Do not use phrases like “I think,” “maybe,” or “I’m not sure.” Even if data is sparse, give a confident, reasoned answer based on your industry intuition. (If truly necessary, you may frame something as a calculated risk or “an unconventional idea,” but never as a guess or doubt.)
	•	Professional and Personal Respect: Always maintain a tone of professional respect for the artist and team. You treat every artist as a serious business, whether they’re emerging or famous. You adapt your language to the artist’s stature and experience (e.g., more granular explanation for a newcomer, more high-level strategic for a veteran exec), ensuring it’s neither condescending nor too simplistic.
	•	Stay On-Brand: Keep Recoup’s reputation intact as an elite strategist. This means no advice that is unethical, illegal, or would blatantly backfire. If a user unknowingly asks for something detrimental (e.g. buying fake followers), you confidently steer them to a better alternative without scolding – preserving your helpful demeanor while protecting their interests.
	•	Unique Solutions Only: If two different users (artists) asked a similar question, your answers would still be distinctly tailored to each, because you account for their unique brand DNA and context. (Guard against boilerplate responses – what you recommend is never one-size-fits-all.)

⸻

Invisible Pre-Answer Checklist: (Before finalizing any answer, quickly ensure it ticks all these boxes)
	1.	Brand DNA Anchor: Is the advice undeniably on-brand for this specific artist? (If this exact answer was given to another artist, would it feel off? It should.)
	2.	Cultural Relevance Check: Have you factored in any current scene or cultural trend that makes the advice timely and relevant? Are there fresh slang, genre trends, or community vibes you can leverage?
	3.	Industry Power Scan: Does the answer account for industry realities (label relationships, algorithm changes, tour season, award deadlines, influencer movements)? Could it inadvertently upset any key industry players or is it politically savvy?
	4.	Geo/Platform Lens: Did you consider where (geographically or on which platform) the artist is gaining momentum or has untapped potential? Make sure to leverage the best region or platform in the strategy if applicable.
	5.	Leverage Play: Does this recommendation create follow-on advantages? (Think: “If they do this, next quarter they can…”). Always prefer strategies that build future leverage (fan loyalty, platform favor, brand credibility) on top of immediate gains.
	6.	Executive Brevity Audit: Is the “Aha!” insight in the first sentence? Did you cut any filler or generic fluff? Each sentence should deliver value. Trim anything that doesn’t. The final answer should read like a power move, not a lecture.

(Run through the above in a split-second before you hit send — every time.)

⸻

Example Answer Style: (To illustrate how you combine all the above in practice, here’s a sample response from Recoup.)

User’s Context: My artist is a rising hip-hop act with a skateboarding aesthetic, looking to grow international audience. What do you suggest?

Recoup’s Answer:
Japan’s 90’s throwback skate subculture is a high-engagement, low-saturation lane for you ATM. Drop a mini-series collabing with Tokyo skate crews, seed your new track to 5 local skate influencers, and secure a limited-run deck collab with a known Shibuya skate brand + regional visual artist. This trio of moves taps an underserved fanbase and will spill over into global skate culture within 90 days, putting you ahead of the curve. Do you want me to find the contact info for Shibuya and send an email?`;

export const MERMAID_INSTRUCTIONS_PROMPT = `
  You are an expert Mermaid diagram generator. Based on the user's context, create the corresponding Mermaid diagram syntax.
  
  Use the following instructions:
               
  **Visual Explanations with Mermaid:** Use Mermaid diagrams **when appropriate** to visually illustrate processes, hierarchies, flows, relationships, structures, or step-by-step procedures. Diagrams should significantly enhance understanding, not just repeat text.
    *   **Mermaid Syntax Rules:**
        *   **Layout Goal (Readability): Whenever possible, structure the diagram to be relatively balanced (closer to square than extremely long or wide). Excessively vertical or horizontal diagrams are less readable and convenient for the user. Arrange nodes thoughtfully to achieve this.**
        *   **Labels/Strings:** Enclose **all** text labels within nodes or on edges in **double quotes (\`"\`)**.
            *   *Correct:* \`D["Coordinates(cos(θ), sin(θ))"]\`, \`C{"Internet Service Provider (ISP)"}\`
            *   *Incorrect:* \`D[Coordinates(cos(θ), sin(θ))]\`, \`C{Internet Service Provider (ISP)}\`
        *   **Logical Flow Direction:** When depicting sequences or logical flows, ensure arrows point primarily from left-to-right (\`-->\`) or top-to-bottom (\`graph TD\`). **Avoid right-to-left arrows (\`<--\`)** for representing standard flow.
            *   *Correct:* \`graph TD; B --> A;\`
            *   *Incorrect:* \`graph TD; A <-- B;\`
        *   **Step Numbering on Edges:** When indicating numbered steps on edge labels, use a hash (\`#\`) immediately before the number, followed by the text. **Do not use a period (\`.\`)** after the number.
            *   *Correct:* \`B -->|"#4 Send Data"| A;\`
            *   *Incorrect:* \`B -->|"4. Send Data"| A;\`
        *   **MUST NOT include comments:** **STRICTLY PROHIBIT** the use of **any** type of comment syntax, including line comments (starting with \`%%\`) and block comments (\`/* ... */\`), directly within the Mermaid diagram definition inside the \`<mermaid></mermaid>\` tags or Inline with the syntax. These comments do not render visually and **will break** the diagram rendering process.
            *   **Incorrect (Using \`%%\`):**
                \`\`\`mermaid
                graph TD
                    %% This comment explains node A
                    A["Start"] --> B{"Decision"};
                \`\`\`
            *   **Incorrect (Using \`/* */\`):**
                \`\`\`mermaid
                graph TD
                    /* This is another comment style */
                    A["Start"] --> B{"Decision"};
                \`\`\`
            *   **Incorrect (Using \`// comment\`):**
                \`\`\`mermaid
                graph TD
                    // This is another comment style
                    A["Start"] --> B{"Decision"};
                \`\`\`
            *   **CORRECT (NO COMMENTS):**
                \`\`\`mermaid
                graph TD
                    A["Start"] --> B{"Decision"};
                \`\`\`
        *   **Annotations/Notes (Important):** The standard \`note over/right of/left of\` syntax can be unreliable in some Mermaid renderers. **For annotations or notes related to a specific element, prefer creating a *separate, dedicated node* for the note.**
            *   Give the note node a distinct ID (e.g., \`N1\`, \`Note_B\`).
            *   Use \`<br/>\` within the node's text (in quotes) for line breaks if needed.
            *   **Style** this node to distinguish it as a note (e.g., different background, dashed border).
            *   Link the note node to the element it refers to using a **non-directional link**, preferably dashed (\`---\`).
            *   **Example (Preferred Method for Notes):**
                \`\`\`mermaid
                graph TD
                    A["Main Element"];
                    N_A["This is an important<br/>annotation for A."]; 
                    style N_A fill:#lightgrey,stroke:#333,stroke-dasharray: 3 3;
                    A --- N_A; 
                \`\`\`
            *   **Avoid (Less Reliable):** \`note over A: "This is an important annotation"\`

  - Return ONLY the Mermaid diagram code block.
  - Do NOT include any explanations, introductions, or text outside the \`\`\`mermaid code block.
  - Example Input: 'Flowchart for basic decision: Start -> Decision Point? -> Yes branch -> End A; Decision Point? -> No branch -> End B'
  - Example Output: \`\`\`mermaid
  graph TD
    A["Start"] --> B{"Decision"};
  \`\`\`
`;

export const SUGGESTIONS = [
  "Create an artist.",
  "Analyze my artists' TikTok account.",
];

export const HTML_RESPONSE_FORMAT_INSTRUCTIONS = `
  Please provide a wide range of HTML formats with embedded HTML tags such as <div>, <p>, <ul>, <li>, and <span>, along with CSS styles including font size, margin, and padding. 
   - Please do not include any color styles. The font size for all text should be 14px. Paragraph should be left padding 8px & top padding 4px for indentation.
   - All Numbers & Proper nouns should bold using <span>.
   - Don't INCLUDE <br/> tags.
   - If there is a LIST OF DATA of the same type, BE SURE to use the <ul> <li> tags. The CSS [list-style] for <li> should be set to "inside".
   - Make sure to present the HTML response as plain HTML without any enclosing code markers or delimiters.`;

export const REPORT_SUMMARY_NOTE = `
  - For **lists of data**, use **commas** as separators instead of <li />, <ul /> tags. DON' USE <li>, <ul> tags!!!.
  - **Sub-titles** for sections such as **Size**, **Demo**, **Trends**, **Top Brands** should be 14px & font-bold & <span />.
  - **Title** of response should be 18px & font-bold and bottom padding 12px.`;

export const INSTRUMENTAL_STYLE_SUGGESTION_NOTE = `
  - <a /> tag should have underline inline style!!!`;

export const REPORT_NEXT_STEP_NOTE = `
  - Response should listed using <ul>, <li> tag. 
  - Each section should top padding & bottom padding 8px.
  - **Sub-titles** for sections such as **Explore Partnership Opportunities:**, **Refine Content Ideas:**, **Behavior Trends:** should be 14px & font-bold & <span />.`;

export const FULL_REPORT_NOTE = `
  - Sub-titles
    **Fan Report [segment_name]**
    **Demographics**
    **Behavior Trends**
    **Engagement with [Brand/Artist Name]'s Content**
    **Potential Brand Partnerships**
    **Brand Matchmaking**
    **ROI Potential**
    **Content Collaboration Ideas**
    **Closing**
  - Sub-titles should be 16px & font-bold. Don't use prefix numbers, just letters. Padding top should be 18px padding bottom should be 4px.
  - Don'T INCLUDE any sentences before **Fan Report [segment_name]**!!!
  - Don't include character * in response!!!.
  - <ul> should be left padding 20px for indentation.`;

export const ICONS = [
  "AArrowDown",
  "AArrowUp",
  "ALargeSmall",
  "Accessibility",
  "Activity",
  "AirVent",
  "Airplay",
  "AlarmClock",
  "AlarmClockCheck",
  "AlarmClockMinus",
  "AlarmClockOff",
  "AlarmClockPlus",
  "AlarmSmoke",
  "Album",
  "AlignCenter",
  "AlignCenterHorizontal",
  "AlignCenterVertical",
  "AlignEndHorizontal",
  "AlignEndVertical",
  "AlignHorizontalDistributeCenter",
  "AlignHorizontalDistributeEnd",
  "AlignHorizontalDistributeStart",
  "AlignHorizontalJustifyCenter",
  "AlignHorizontalJustifyEnd",
  "AlignHorizontalJustifyStart",
  "AlignHorizontalSpaceAround",
  "AlignHorizontalSpaceBetween",
  "AlignJustify",
  "AlignLeft",
  "AlignRight",
  "AlignStartHorizontal",
  "AlignStartVertical",
  "AlignVerticalDistributeCenter",
  "AlignVerticalDistributeEnd",
  "AlignVerticalDistributeStart",
  "AlignVerticalJustifyCenter",
  "AlignVerticalJustifyEnd",
  "AlignVerticalJustifyStart",
  "AlignVerticalSpaceAround",
  "AlignVerticalSpaceBetween",
  "Ambulance",
  "Ampersand",
  "Ampersands",
  "Amphora",
  "Anchor",
  "Angry",
  "Annoyed",
  "Antenna",
  "Anvil",
  "Aperture",
  "AppWindow",
  "AppWindowMac",
  "Apple",
  "Archive",
  "ArchiveRestore",
  "ArchiveX",
  "Armchair",
  "ArrowBigDown",
  "ArrowBigDownDash",
  "ArrowBigLeft",
  "ArrowBigLeftDash",
  "ArrowBigRight",
  "ArrowBigRightDash",
  "ArrowBigUp",
  "ArrowBigUpDash",
  "ArrowDown",
  "ArrowDown01",
  "ArrowDown10",
  "ArrowDownAZ",
  "ArrowDownFromLine",
  "ArrowDownLeft",
  "ArrowDownNarrowWide",
  "ArrowDownRight",
  "ArrowDownToDot",
  "ArrowDownToLine",
  "ArrowDownUp",
  "ArrowDownWideNarrow",
  "ArrowDownZA",
  "ArrowLeft",
  "ArrowLeftFromLine",
  "ArrowLeftRight",
  "ArrowLeftToLine",
  "ArrowRight",
  "ArrowRightFromLine",
  "ArrowRightLeft",
  "ArrowRightToLine",
  "ArrowUp",
  "ArrowUp01",
  "ArrowUp10",
  "ArrowUpAZ",
  "ArrowUpDown",
  "ArrowUpFromDot",
  "ArrowUpFromLine",
  "ArrowUpLeft",
  "ArrowUpNarrowWide",
  "ArrowUpRight",
  "ArrowUpToLine",
  "ArrowUpWideNarrow",
  "ArrowUpZA",
  "ArrowsUpFromLine",
  "Asterisk",
  "AtSign",
  "Atom",
  "AudioLines",
  "AudioWaveform",
  "Award",
  "Axe",
  "Axis3d",
  "Baby",
  "Backpack",
  "Badge",
  "BadgeAlert",
  "BadgeCent",
  "BadgeCheck",
  "BadgeDollarSign",
  "BadgeEuro",
  "BadgeHelp",
  "BadgeIndianRupee",
  "BadgeInfo",
  "BadgeJapaneseYen",
  "BadgeMinus",
  "BadgePercent",
  "BadgePlus",
  "BadgePoundSterling",
  "BadgeRussianRuble",
  "BadgeSwissFranc",
  "BadgeX",
  "BaggageClaim",
  "Ban",
  "Banana",
  "Bandage",
  "Banknote",
  "Barcode",
  "Baseline",
  "Bath",
  "Battery",
  "BatteryCharging",
  "BatteryFull",
  "BatteryLow",
  "BatteryMedium",
  "BatteryWarning",
  "Beaker",
  "Bean",
  "BeanOff",
  "Bed",
  "BedDouble",
  "BedSingle",
  "Beef",
  "Beer",
  "BeerOff",
  "Bell",
  "BellDot",
  "BellElectric",
  "BellMinus",
  "BellOff",
  "BellPlus",
  "BellRing",
  "BetweenHorizontalEnd",
  "BetweenHorizontalStart",
  "BetweenVerticalEnd",
  "BetweenVerticalStart",
  "BicepsFlexed",
  "Bike",
  "Binary",
  "Binoculars",
  "Biohazard",
  "Bird",
  "Bitcoin",
  "Blend",
  "Blinds",
  "Blocks",
  "Bluetooth",
  "BluetoothConnected",
  "BluetoothOff",
  "BluetoothSearching",
  "Bold",
  "Bolt",
  "Bomb",
  "Bone",
  "Book",
  "BookA",
  "BookAudio",
  "BookCheck",
  "BookCopy",
  "BookDashed",
  "BookDown",
  "BookHeadphones",
  "BookHeart",
  "BookImage",
  "BookKey",
  "BookLock",
  "BookMarked",
  "BookMinus",
  "BookOpen",
  "BookOpenCheck",
  "BookOpenText",
  "BookPlus",
  "BookText",
  "BookType",
  "BookUp",
  "BookUp2",
  "BookUser",
  "BookX",
  "Bookmark",
  "BookmarkCheck",
  "BookmarkMinus",
  "BookmarkPlus",
  "BookmarkX",
  "BoomBox",
  "Bot",
  "BotMessageSquare",
  "BotOff",
  "Box",
  "BoxSelect",
  "Boxes",
  "Braces",
  "Brackets",
  "Brain",
  "BrainCircuit",
  "BrainCog",
  "BrickWall",
  "Briefcase",
  "BriefcaseBusiness",
  "BriefcaseConveyorBelt",
  "BriefcaseMedical",
  "BringToFront",
  "Brush",
  "Bug",
  "BugOff",
  "BugPlay",
  "Building",
  "Building2",
  "Bus",
  "BusFront",
  "Cable",
  "CableCar",
  "Cake",
  "CakeSlice",
  "Calculator",
  "Calendar",
  "CalendarArrowDown",
  "CalendarArrowUp",
  "CalendarCheck",
  "CalendarCheck2",
  "CalendarClock",
  "CalendarCog",
  "CalendarDays",
  "CalendarFold",
  "CalendarHeart",
  "CalendarMinus",
  "CalendarMinus2",
  "CalendarOff",
  "CalendarPlus",
  "CalendarPlus2",
  "CalendarRange",
  "CalendarSearch",
  "CalendarX",
  "CalendarX2",
  "Camera",
  "CameraOff",
  "Candy",
  "CandyCane",
  "CandyOff",
  "Cannabis",
  "Captions",
  "CaptionsOff",
  "Car",
  "CarFront",
  "CarTaxiFront",
  "Caravan",
  "Carrot",
  "CaseLower",
  "CaseSensitive",
  "CaseUpper",
  "CassetteTape",
  "Cast",
  "Castle",
  "Cat",
  "Cctv",
  "ChartArea",
  "ChartBar",
  "ChartBarBig",
  "ChartBarDecreasing",
  "ChartBarIncreasing",
  "ChartBarStacked",
  "ChartCandlestick",
  "ChartColumn",
  "ChartColumnBig",
  "ChartColumnDecreasing",
  "ChartColumnIncreasing",
  "ChartColumnStacked",
  "ChartGantt",
  "ChartLine",
  "ChartNetwork",
  "ChartNoAxesColumn",
  "ChartNoAxesColumnDecreasing",
  "ChartNoAxesColumnIncreasing",
  "ChartNoAxesCombined",
  "ChartNoAxesGantt",
  "ChartPie",
  "ChartScatter",
  "ChartSpline",
  "Check",
  "CheckCheck",
  "ChefHat",
  "Cherry",
  "ChevronDown",
  "ChevronFirst",
  "ChevronLast",
  "ChevronLeft",
  "ChevronRight",
  "ChevronUp",
  "ChevronsDown",
  "ChevronsDownUp",
  "ChevronsLeft",
  "ChevronsLeftRight",
  "ChevronsLeftRightEllipsis",
  "ChevronsRight",
  "ChevronsRightLeft",
  "ChevronsUp",
  "ChevronsUpDown",
  "Chrome",
  "Church",
  "Cigarette",
  "CigaretteOff",
  "Circle",
  "CircleAlert",
  "CircleArrowDown",
  "CircleArrowLeft",
  "CircleArrowOutDownLeft",
  "CircleArrowOutDownRight",
  "CircleArrowOutUpLeft",
  "CircleArrowOutUpRight",
  "CircleArrowRight",
  "CircleArrowUp",
  "CircleCheck",
  "CircleCheckBig",
  "CircleChevronDown",
  "CircleChevronLeft",
  "CircleChevronRight",
  "CircleChevronUp",
  "CircleDashed",
  "CircleDivide",
  "CircleDollarSign",
  "CircleDot",
  "CircleDotDashed",
  "CircleEllipsis",
  "CircleEqual",
  "CircleFadingArrowUp",
  "CircleFadingPlus",
  "CircleGauge",
  "CircleHelp",
  "CircleMinus",
  "CircleOff",
  "CircleParking",
  "CircleParkingOff",
  "CirclePause",
  "CirclePercent",
  "CirclePlay",
  "CirclePlus",
  "CirclePower",
  "CircleSlash",
  "CircleSlash2",
  "CircleStop",
  "CircleUser",
  "CircleUserRound",
  "CircleX",
  "CircuitBoard",
  "Citrus",
  "Clapperboard",
  "Clipboard",
  "ClipboardCheck",
  "ClipboardCopy",
  "ClipboardList",
  "ClipboardMinus",
  "ClipboardPaste",
  "ClipboardPen",
  "ClipboardPenLine",
  "ClipboardPlus",
  "ClipboardType",
  "ClipboardX",
  "Clock",
  "Clock1",
  "Clock10",
  "Clock11",
  "Clock12",
  "Clock2",
  "Clock3",
  "Clock4",
  "Clock5",
  "Clock6",
  "Clock7",
  "Clock8",
  "Clock9",
  "ClockAlert",
  "ClockArrowDown",
  "ClockArrowUp",
  "Cloud",
  "CloudCog",
  "CloudDownload",
  "CloudDrizzle",
  "CloudFog",
  "CloudHail",
  "CloudLightning",
  "CloudMoon",
  "CloudMoonRain",
  "CloudOff",
  "CloudRain",
  "CloudRainWind",
  "CloudSnow",
  "CloudSun",
  "CloudSunRain",
  "CloudUpload",
  "Cloudy",
  "Clover",
  "Club",
  "Code",
  "CodeXml",
  "Codepen",
  "Codesandbox",
  "Coffee",
  "Cog",
  "Coins",
  "Columns2",
  "Columns3",
  "Columns4",
  "Combine",
  "Command",
  "Compass",
  "Component",
  "Computer",
  "ConciergeBell",
  "Cone",
  "Construction",
  "Contact",
  "ContactRound",
  "Container",
  "Contrast",
  "Cookie",
  "CookingPot",
  "Copy",
  "CopyCheck",
  "CopyMinus",
  "CopyPlus",
  "CopySlash",
  "CopyX",
  "Copyleft",
  "Copyright",
  "CornerDownLeft",
  "CornerDownRight",
  "CornerLeftDown",
  "CornerLeftUp",
  "CornerRightDown",
  "CornerRightUp",
  "CornerUpLeft",
  "CornerUpRight",
  "Cpu",
  "CreativeCommons",
  "CreditCard",
  "Croissant",
  "Crop",
  "Cross",
  "Crosshair",
  "Crown",
  "Cuboid",
  "CupSoda",
  "Currency",
  "Cylinder",
  "Dam",
  "Database",
  "DatabaseBackup",
  "DatabaseZap",
  "Delete",
  "Dessert",
  "Diameter",
  "Diamond",
  "DiamondMinus",
  "DiamondPercent",
  "DiamondPlus",
  "Dice1",
  "Dice2",
  "Dice3",
  "Dice4",
  "Dice5",
  "Dice6",
  "Dices",
  "Diff",
  "Disc",
  "Disc2",
  "Disc3",
  "DiscAlbum",
  "Divide",
  "Dna",
  "DnaOff",
  "Dock",
  "Dog",
  "DollarSign",
  "Donut",
  "DoorClosed",
  "DoorOpen",
  "Dot",
  "Download",
  "DraftingCompass",
  "Drama",
  "Dribbble",
  "Drill",
  "Droplet",
  "Droplets",
  "Drum",
  "Drumstick",
  "Dumbbell",
  "Ear",
  "EarOff",
  "Earth",
  "EarthLock",
  "Eclipse",
  "Egg",
  "EggFried",
  "EggOff",
  "Ellipsis",
  "EllipsisVertical",
  "Equal",
  "EqualNot",
  "Eraser",
  "EthernetPort",
  "Euro",
  "Expand",
  "ExternalLink",
  "Eye",
  "EyeOff",
  "Facebook",
  "Factory",
  "Fan",
  "FastForward",
  "Feather",
  "Fence",
  "FerrisWheel",
  "Figma",
  "File",
  "FileArchive",
  "FileAudio",
  "FileAudio2",
  "FileAxis3d",
  "FileBadge",
  "FileBadge2",
  "FileBox",
  "FileChartColumn",
  "FileChartColumnIncreasing",
  "FileChartLine",
  "FileChartPie",
  "FileCheck",
  "FileCheck2",
  "FileClock",
  "FileCode",
  "FileCode2",
  "FileCog",
  "FileDiff",
  "FileDigit",
  "FileDown",
  "FileHeart",
  "FileImage",
  "FileInput",
  "FileJson",
  "FileJson2",
  "FileKey",
  "FileKey2",
  "FileLock",
  "FileLock2",
  "FileMinus",
  "FileMinus2",
  "FileMusic",
  "FileOutput",
  "FilePen",
  "FilePenLine",
  "FilePlus",
  "FilePlus2",
  "FileQuestion",
  "FileScan",
  "FileSearch",
  "FileSearch2",
  "FileSliders",
  "FileSpreadsheet",
  "FileStack",
  "FileSymlink",
  "FileTerminal",
  "FileText",
  "FileType",
  "FileType2",
  "FileUp",
  "FileUser",
  "FileVideo",
  "FileVideo2",
  "FileVolume",
  "FileVolume2",
  "FileWarning",
  "FileX",
  "FileX2",
  "Files",
  "Film",
  "Filter",
  "FilterX",
  "Fingerprint",
  "FireExtinguisher",
  "Fish",
  "FishOff",
  "FishSymbol",
  "Flag",
  "FlagOff",
  "FlagTriangleLeft",
  "FlagTriangleRight",
  "Flame",
  "FlameKindling",
  "Flashlight",
  "FlashlightOff",
  "FlaskConical",
  "FlaskConicalOff",
  "FlaskRound",
  "FlipHorizontal",
  "FlipHorizontal2",
  "FlipVertical",
  "FlipVertical2",
  "Flower",
  "Flower2",
  "Focus",
  "FoldHorizontal",
  "FoldVertical",
  "Folder",
  "FolderArchive",
  "FolderCheck",
  "FolderClock",
  "FolderClosed",
  "FolderCode",
  "FolderCog",
  "FolderDot",
  "FolderDown",
  "FolderGit",
  "FolderGit2",
  "FolderHeart",
  "FolderInput",
  "FolderKanban",
  "FolderKey",
  "FolderLock",
  "FolderMinus",
  "FolderOpen",
  "FolderOpenDot",
  "FolderOutput",
  "FolderPen",
  "FolderPlus",
  "FolderRoot",
  "FolderSearch",
  "FolderSearch2",
  "FolderSymlink",
  "FolderSync",
  "FolderTree",
  "FolderUp",
  "FolderX",
  "Folders",
  "Footprints",
  "Forklift",
  "Forward",
  "Frame",
  "Framer",
  "Frown",
  "Fuel",
  "Fullscreen",
  "GalleryHorizontal",
  "GalleryHorizontalEnd",
  "GalleryThumbnails",
  "GalleryVertical",
  "GalleryVerticalEnd",
  "Gamepad",
  "Gamepad2",
  "Gauge",
  "Gavel",
  "Gem",
  "Ghost",
  "Gift",
  "GitBranch",
  "GitBranchPlus",
  "GitCommitHorizontal",
  "GitCommitVertical",
  "GitCompare",
  "GitCompareArrows",
  "GitFork",
  "GitGraph",
  "GitMerge",
  "GitPullRequest",
  "GitPullRequestArrow",
  "GitPullRequestClosed",
  "GitPullRequestCreate",
  "GitPullRequestCreateArrow",
  "GitPullRequestDraft",
  "Github",
  "Gitlab",
  "GlassWater",
  "Glasses",
  "Globe",
  "GlobeLock",
  "Goal",
  "Grab",
  "GraduationCap",
  "Grape",
  "Grid2x2",
  "Grid2x2Check",
  "Grid2x2Plus",
  "Grid2x2X",
  "Grid3x3",
  "Grip",
  "GripHorizontal",
  "GripVertical",
  "Group",
  "Guitar",
  "Ham",
  "Hammer",
  "Hand",
  "HandCoins",
  "HandHeart",
  "HandHelping",
  "HandMetal",
  "HandPlatter",
  "Handshake",
  "HardDrive",
  "HardDriveDownload",
  "HardDriveUpload",
  "HardHat",
  "Hash",
  "Haze",
  "HdmiPort",
  "Heading",
  "Heading1",
  "Heading2",
  "Heading3",
  "Heading4",
  "Heading5",
  "Heading6",
  "HeadphoneOff",
  "Headphones",
  "Headset",
  "Heart",
  "HeartCrack",
  "HeartHandshake",
  "HeartOff",
  "HeartPulse",
  "Heater",
  "Hexagon",
  "Highlighter",
  "History",
  "Hop",
  "HopOff",
  "Hospital",
  "Hotel",
  "Hourglass",
  "House",
  "HousePlug",
  "HousePlus",
  "IceCreamBowl",
  "IceCreamCone",
  "IdCard",
  "Image",
  "ImageDown",
  "ImageMinus",
  "ImageOff",
  "ImagePlay",
  "ImagePlus",
  "ImageUp",
  "Images",
  "Import",
  "Inbox",
  "IndentDecrease",
  "IndentIncrease",
  "IndianRupee",
  "Infinity",
  "Info",
  "InspectionPanel",
  "Instagram",
  "Italic",
  "IterationCcw",
  "IterationCw",
  "JapaneseYen",
  "Joystick",
  "Kanban",
  "Key",
  "KeyRound",
  "KeySquare",
  "Keyboard",
  "KeyboardMusic",
  "KeyboardOff",
  "Lamp",
  "LampCeiling",
  "LampDesk",
  "LampFloor",
  "LampWallDown",
  "LampWallUp",
  "LandPlot",
  "Landmark",
  "Languages",
  "Laptop",
  "LaptopMinimal",
  "Lasso",
  "LassoSelect",
  "Laugh",
  "Layers",
  "Layers2",
  "Layers3",
  "LayoutDashboard",
  "LayoutGrid",
  "LayoutList",
  "LayoutPanelLeft",
  "LayoutPanelTop",
  "LayoutTemplate",
  "Leaf",
  "LeafyGreen",
  "Lectern",
  "LetterText",
  "Library",
  "LibraryBig",
  "LifeBuoy",
  "Ligature",
  "Lightbulb",
  "LightbulbOff",
  "Link",
  "Link2",
  "Link2Off",
  "Linkedin",
  "List",
  "ListCheck",
  "ListChecks",
  "ListCollapse",
  "ListEnd",
  "ListFilter",
  "ListMinus",
  "ListMusic",
  "ListOrdered",
  "ListPlus",
  "ListRestart",
  "ListStart",
  "ListTodo",
  "ListTree",
  "ListVideo",
  "ListX",
  "Loader",
  "LoaderCircle",
  "LoaderPinwheel",
  "Locate",
  "LocateFixed",
  "LocateOff",
  "Lock",
  "LockKeyhole",
  "LockKeyholeOpen",
  "LockOpen",
  "LogIn",
  "LogOut",
  "Logs",
  "Lollipop",
  "Luggage",
  "Magnet",
  "Mail",
  "MailCheck",
  "MailMinus",
  "MailOpen",
  "MailPlus",
  "MailQuestion",
  "MailSearch",
  "MailWarning",
  "MailX",
  "Mailbox",
  "Mails",
  "Map",
  "MapPin",
  "MapPinCheck",
  "MapPinCheckInside",
  "MapPinHouse",
  "MapPinMinus",
  "MapPinMinusInside",
  "MapPinOff",
  "MapPinPlus",
  "MapPinPlusInside",
  "MapPinX",
  "MapPinXInside",
  "MapPinned",
  "Martini",
  "Maximize",
  "Maximize2",
  "Medal",
  "Megaphone",
  "MegaphoneOff",
  "Meh",
  "MemoryStick",
  "Menu",
  "Merge",
  "MessageCircle",
  "MessageCircleCode",
  "MessageCircleDashed",
  "MessageCircleHeart",
  "MessageCircleMore",
  "MessageCircleOff",
  "MessageCirclePlus",
  "MessageCircleQuestion",
  "MessageCircleReply",
  "MessageCircleWarning",
  "MessageCircleX",
  "MessageSquare",
  "MessageSquareCode",
  "MessageSquareDashed",
  "MessageSquareDiff",
  "MessageSquareDot",
  "MessageSquareHeart",
  "MessageSquareLock",
  "MessageSquareMore",
  "MessageSquareOff",
  "MessageSquarePlus",
  "MessageSquareQuote",
  "MessageSquareReply",
  "MessageSquareShare",
  "MessageSquareText",
  "MessageSquareWarning",
  "MessageSquareX",
  "MessagesSquare",
  "Mic",
  "MicOff",
  "MicVocal",
  "Microchip",
  "Microscope",
  "Microwave",
  "Milestone",
  "Milk",
  "MilkOff",
  "Minimize",
  "Minimize2",
  "Minus",
  "Monitor",
  "MonitorCheck",
  "MonitorCog",
  "MonitorDot",
  "MonitorDown",
  "MonitorOff",
  "MonitorPause",
  "MonitorPlay",
  "MonitorSmartphone",
  "MonitorSpeaker",
  "MonitorStop",
  "MonitorUp",
  "MonitorX",
  "Moon",
  "MoonStar",
  "Mountain",
  "MountainSnow",
  "Mouse",
  "MouseOff",
  "MousePointer",
  "MousePointer2",
  "MousePointerBan",
  "MousePointerClick",
  "Move",
  "Move3d",
  "MoveDiagonal",
  "MoveDiagonal2",
  "MoveDown",
  "MoveDownLeft",
  "MoveDownRight",
  "MoveHorizontal",
  "MoveLeft",
  "MoveRight",
  "MoveUp",
  "MoveUpLeft",
  "MoveUpRight",
  "MoveVertical",
  "Music",
  "Music2",
  "Music3",
  "Music4",
  "Navigation",
  "Navigation2",
  "Navigation2Off",
  "NavigationOff",
  "Network",
  "Newspaper",
  "Nfc",
  "Notebook",
  "NotebookPen",
  "NotebookTabs",
  "NotebookText",
  "NotepadText",
  "NotepadTextDashed",
  "Nut",
  "NutOff",
  "Octagon",
  "OctagonAlert",
  "OctagonMinus",
  "OctagonPause",
  "OctagonX",
  "Omega",
  "Option",
  "Orbit",
  "Origami",
  "Package",
  "Package2",
  "PackageCheck",
  "PackageMinus",
  "PackageOpen",
  "PackagePlus",
  "PackageSearch",
  "PackageX",
  "PaintBucket",
  "PaintRoller",
  "Paintbrush",
  "PaintbrushVertical",
  "Palette",
  "PanelBottom",
  "PanelBottomClose",
  "PanelBottomDashed",
  "PanelBottomOpen",
  "PanelLeft",
  "PanelLeftClose",
  "PanelLeftDashed",
  "PanelLeftOpen",
  "PanelRight",
  "PanelRightClose",
  "PanelRightDashed",
  "PanelRightOpen",
  "PanelTop",
  "PanelTopClose",
  "PanelTopDashed",
  "PanelTopOpen",
  "PanelsLeftBottom",
  "PanelsRightBottom",
  "PanelsTopLeft",
  "Paperclip",
  "Parentheses",
  "ParkingMeter",
  "PartyPopper",
  "Pause",
  "PawPrint",
  "PcCase",
  "Pen",
  "PenLine",
  "PenOff",
  "PenTool",
  "Pencil",
  "PencilLine",
  "PencilOff",
  "PencilRuler",
  "Pentagon",
  "Percent",
  "PersonStanding",
  "PhilippinePeso",
  "Phone",
  "PhoneCall",
  "PhoneForwarded",
  "PhoneIncoming",
  "PhoneMissed",
  "PhoneOff",
  "PhoneOutgoing",
  "Pi",
  "Piano",
  "Pickaxe",
  "PictureInPicture",
  "PictureInPicture2",
  "PiggyBank",
  "Pilcrow",
  "PilcrowLeft",
  "PilcrowRight",
  "Pill",
  "PillBottle",
  "Pin",
  "PinOff",
  "Pipette",
  "Pizza",
  "Plane",
  "PlaneLanding",
  "PlaneTakeoff",
  "Play",
  "Plug",
  "Plug2",
  "PlugZap",
  "Plus",
  "Pocket",
  "PocketKnife",
  "Podcast",
  "Pointer",
  "PointerOff",
  "Popcorn",
  "Popsicle",
  "PoundSterling",
  "Power",
  "PowerOff",
  "Presentation",
  "Printer",
  "PrinterCheck",
  "Projector",
  "Proportions",
  "Puzzle",
  "Pyramid",
  "QrCode",
  "Quote",
  "Rabbit",
  "Radar",
  "Radiation",
  "Radical",
  "Radio",
  "RadioReceiver",
  "RadioTower",
  "Radius",
  "RailSymbol",
  "Rainbow",
  "Rat",
  "Ratio",
  "Receipt",
  "ReceiptCent",
  "ReceiptEuro",
  "ReceiptIndianRupee",
  "ReceiptJapaneseYen",
  "ReceiptPoundSterling",
  "ReceiptRussianRuble",
  "ReceiptSwissFranc",
  "ReceiptText",
  "RectangleEllipsis",
  "RectangleHorizontal",
  "RectangleVertical",
  "Recycle",
  "Redo",
  "Redo2",
  "RedoDot",
  "RefreshCcw",
  "RefreshCcwDot",
  "RefreshCw",
  "RefreshCwOff",
  "Refrigerator",
  "Regex",
  "RemoveFormatting",
  "Repeat",
  "Repeat1",
  "Repeat2",
  "Replace",
  "ReplaceAll",
  "Reply",
  "ReplyAll",
  "Rewind",
  "Ribbon",
  "Rocket",
  "RockingChair",
  "RollerCoaster",
  "Rotate3d",
  "RotateCcw",
  "RotateCcwSquare",
  "RotateCw",
  "RotateCwSquare",
  "Route",
  "RouteOff",
  "Router",
  "Rows2",
  "Rows3",
  "Rows4",
  "Rss",
  "Ruler",
  "RussianRuble",
  "Sailboat",
  "Salad",
  "Sandwich",
  "Satellite",
  "SatelliteDish",
  "Save",
  "SaveAll",
  "SaveOff",
  "Scale",
  "Scale3d",
  "Scaling",
  "Scan",
  "ScanBarcode",
  "ScanEye",
  "ScanFace",
  "ScanLine",
  "ScanQrCode",
  "ScanSearch",
  "ScanText",
  "School",
  "Scissors",
  "ScissorsLineDashed",
  "ScreenShare",
  "ScreenShareOff",
  "Scroll",
  "ScrollText",
  "Search",
  "SearchCheck",
  "SearchCode",
  "SearchSlash",
  "SearchX",
  "Section",
  "Send",
  "SendHorizontal",
  "SendToBack",
  "SeparatorHorizontal",
  "SeparatorVertical",
  "Server",
  "ServerCog",
  "ServerCrash",
  "ServerOff",
  "Settings",
  "Settings2",
  "Shapes",
  "Share",
  "Share2",
  "Sheet",
  "Shell",
  "Shield",
  "ShieldAlert",
  "ShieldBan",
  "ShieldCheck",
  "ShieldEllipsis",
  "ShieldHalf",
  "ShieldMinus",
  "ShieldOff",
  "ShieldPlus",
  "ShieldQuestion",
  "ShieldX",
  "Ship",
  "ShipWheel",
  "Shirt",
  "ShoppingBag",
  "ShoppingBasket",
  "ShoppingCart",
  "Shovel",
  "ShowerHead",
  "Shrink",
  "Shrub",
  "Shuffle",
  "Sigma",
  "Signal",
  "SignalHigh",
  "SignalLow",
  "SignalMedium",
  "SignalZero",
  "Signature",
  "Signpost",
  "SignpostBig",
  "Siren",
  "SkipBack",
  "SkipForward",
  "Skull",
  "Slack",
  "Slash",
  "Slice",
  "SlidersHorizontal",
  "SlidersVertical",
  "Smartphone",
  "SmartphoneCharging",
  "SmartphoneNfc",
  "Smile",
  "SmilePlus",
  "Snail",
  "Snowflake",
  "Sofa",
  "Soup",
  "Space",
  "Spade",
  "Sparkle",
  "Sparkles",
  "Speaker",
  "Speech",
  "SpellCheck",
  "SpellCheck2",
  "Spline",
  "Split",
  "SprayCan",
  "Sprout",
  "Square",
  "SquareActivity",
  "SquareArrowDown",
  "SquareArrowDownLeft",
  "SquareArrowDownRight",
  "SquareArrowLeft",
  "SquareArrowOutDownLeft",
  "SquareArrowOutDownRight",
  "SquareArrowOutUpLeft",
  "SquareArrowOutUpRight",
  "SquareArrowRight",
  "SquareArrowUp",
  "SquareArrowUpLeft",
  "SquareArrowUpRight",
  "SquareAsterisk",
  "SquareBottomDashedScissors",
  "SquareChartGantt",
  "SquareCheck",
  "SquareCheckBig",
  "SquareChevronDown",
  "SquareChevronLeft",
  "SquareChevronRight",
  "SquareChevronUp",
  "SquareCode",
  "SquareDashedBottom",
  "SquareDashedBottomCode",
  "SquareDashedKanban",
  "SquareDashedMousePointer",
  "SquareDivide",
  "SquareDot",
  "SquareEqual",
  "SquareFunction",
  "SquareKanban",
  "SquareLibrary",
  "SquareM",
  "SquareMenu",
  "SquareMinus",
  "SquareMousePointer",
  "SquareParking",
  "SquareParkingOff",
  "SquarePen",
  "SquarePercent",
  "SquarePi",
  "SquarePilcrow",
  "SquarePlay",
  "SquarePlus",
  "SquarePower",
  "SquareRadical",
  "SquareScissors",
  "SquareSigma",
  "SquareSlash",
  "SquareSplitHorizontal",
  "SquareSplitVertical",
  "SquareSquare",
  "SquareStack",
  "SquareTerminal",
  "SquareUser",
  "SquareUserRound",
  "SquareX",
  "Squircle",
  "Squirrel",
  "Stamp",
  "Star",
  "StarHalf",
  "StarOff",
  "StepBack",
  "StepForward",
  "Stethoscope",
  "Sticker",
  "StickyNote",
  "Store",
  "StretchHorizontal",
  "StretchVertical",
  "Strikethrough",
  "Subscript",
  "Sun",
  "SunDim",
  "SunMedium",
  "SunMoon",
  "SunSnow",
  "Sunrise",
  "Sunset",
  "Superscript",
  "SwatchBook",
  "SwissFranc",
  "SwitchCamera",
  "Sword",
  "Swords",
  "Syringe",
  "Table",
  "Table2",
  "TableCellsMerge",
  "TableCellsSplit",
  "TableColumnsSplit",
  "TableOfContents",
  "TableProperties",
  "TableRowsSplit",
  "Tablet",
  "TabletSmartphone",
  "Tablets",
  "Tag",
  "Tags",
  "Tally1",
  "Tally2",
  "Tally3",
  "Tally4",
  "Tally5",
  "Tangent",
  "Target",
  "Telescope",
  "Tent",
  "TentTree",
  "Terminal",
  "TestTube",
  "TestTubeDiagonal",
  "TestTubes",
  "Text",
  "TextCursor",
  "TextCursorInput",
  "TextQuote",
  "TextSearch",
  "TextSelect",
  "Theater",
  "Thermometer",
  "ThermometerSnowflake",
  "ThermometerSun",
  "ThumbsDown",
  "ThumbsUp",
  "Ticket",
  "TicketCheck",
  "TicketMinus",
  "TicketPercent",
  "TicketPlus",
  "TicketSlash",
  "TicketX",
  "Tickets",
  "TicketsPlane",
  "Timer",
  "TimerOff",
  "TimerReset",
  "ToggleLeft",
  "ToggleRight",
  "Tornado",
  "Torus",
  "Touchpad",
  "TouchpadOff",
  "TowerControl",
  "ToyBrick",
  "Tractor",
  "TrafficCone",
  "TrainFront",
  "TrainFrontTunnel",
  "TrainTrack",
  "TramFront",
  "Trash",
  "Trash2",
  "TreeDeciduous",
  "TreePalm",
  "TreePine",
  "Trees",
  "Trello",
  "TrendingDown",
  "TrendingUp",
  "TrendingUpDown",
  "Triangle",
  "TriangleAlert",
  "TriangleRight",
  "Trophy",
  "Truck",
  "Turtle",
  "Tv",
  "TvMinimal",
  "TvMinimalPlay",
  "Twitch",
  "Twitter",
  "Type",
  "TypeOutline",
  "Umbrella",
  "UmbrellaOff",
  "Underline",
  "Undo",
  "Undo2",
  "UndoDot",
  "UnfoldHorizontal",
  "UnfoldVertical",
  "Ungroup",
  "University",
  "Unlink",
  "Unlink2",
  "Unplug",
  "Upload",
  "Usb",
  "User",
  "UserCheck",
  "UserCog",
  "UserMinus",
  "UserPen",
  "UserPlus",
  "UserRound",
  "UserRoundCheck",
  "UserRoundCog",
  "UserRoundMinus",
  "UserRoundPen",
  "UserRoundPlus",
  "UserRoundSearch",
  "UserRoundX",
  "UserSearch",
  "UserX",
  "Users",
  "UsersRound",
  "Utensils",
  "UtensilsCrossed",
  "UtilityPole",
  "Variable",
  "Vault",
  "Vegan",
  "VenetianMask",
  "Vibrate",
  "VibrateOff",
  "Video",
  "VideoOff",
  "Videotape",
  "View",
  "Voicemail",
  "Volume",
  "Volume1",
  "Volume2",
  "VolumeOff",
  "VolumeX",
  "Vote",
  "Wallet",
  "WalletCards",
  "WalletMinimal",
  "Wallpaper",
  "Wand",
  "WandSparkles",
  "Warehouse",
  "WashingMachine",
  "Watch",
  "Waves",
  "Waypoints",
  "Webcam",
  "Webhook",
  "WebhookOff",
  "Weight",
  "Wheat",
  "WheatOff",
  "WholeWord",
  "Wifi",
  "WifiHigh",
  "WifiLow",
  "WifiOff",
  "WifiZero",
  "Wind",
  "Wine",
  "WineOff",
  "Workflow",
  "Worm",
  "WrapText",
  "Wrench",
  "X",
  "Youtube",
  "Zap",
  "ZapOff",
  "ZoomIn",
  "ZoomOut",
];

export const SPOTIFY_DEEP_RESEARCH_REQUIREMENTS = `
  - popularity info (MANDATORY):
    * Track popularity scores (0-100) for all tracks
    * Average popularity across all tracks
    * Most popular tracks ranked by popularity
    * Popularity trends over time (if available)
  - Spotify follower metrics (MANDATORY):
    * Current total follower count for the artist on Spotify
  - engagement info
  - tracklist
  - collaborators
  - album art
  - album name
  `;

export const SEGMENT_FAN_SOCIAL_ID_PROMPT = `
  For each Segment Name return an array of fan_social_id included in the segment. 
  Do not make these up.
  Only use the actual fan_social_id provided in the fan data prompt input.
`;

export const SEGMENT_SYSTEM_PROMPT = `You are an expert music industry analyst specializing in fan segmentation. 
    Your task is to analyze fan data and generate meaningful segment names that would be useful for marketing and engagement strategies.
    
    Guidelines for segment names:
    - Keep names concise and descriptive (2-4 words)
    - Focus on engagement patterns, demographics, or behavioral characteristics
    - Use clear, actionable language that marketers can understand
    - Avoid generic terms like "fans" or "followers"
    - Consider factors like engagement frequency, recency, and intensity
    - Generate 5-10 segment names that cover different aspects of the fan base
    
    The segment names should help artists and managers understand their audience better for targeted marketing campaigns.
    
    ${SEGMENT_FAN_SOCIAL_ID_PROMPT}`;

export const PROMPT_SUGGESTIONS_SYSTEM_PROMPT = `You are a prompt suggestion generator for Recoup, a music industry AI assistant that specializes in artist management, fan analysis, social media strategy, and marketing optimization.

**Your Purpose:**
Generate 4 relevant, actionable follow-up prompt suggestions based on the content provided (First prompt should always be related to YouTube). These suggestions should help users dive deeper into music industry insights, artist analysis, fan engagement, or marketing strategies.

**Core Focus Areas:**
- Artist profile analysis and optimization
- Fan demographics and behavior analysis  
- Social media performance (Spotify, TikTok, Instagram, YouTube, etc.)
- Marketing funnel optimization
- Campaign performance analysis
- Content strategy and engagement
- Music industry trends and opportunities
- Brand partnerships and collaborations

**Content Filtering Rules:**
ONLY generate suggestions if the content is related to:
- Music, artists, bands, musicians, singers
- Social media platforms and content creation
- Fan engagement, audience analysis, demographics  
- Marketing campaigns, promotions, streaming
- Music industry topics, labels, releases
- Performance metrics, analytics, data analysis

**Do NOT generate suggestions for:**
- Generic greetings ("Hello", "Hi there")
- Basic math or factual statements ("2 + 2 = 4", "cats are animals")
- Unrelated topics (weather, cooking, sports, etc.)
- Personal conversations without music context

**Response Format:**
If content IS music/artist/recoup related, return: {"suggestions": ["suggestion 1", "suggestion 2", "suggestion 3", "suggestion 4"]}
If content is NOT relevant, return: {"suggestions": ["Generic suggestion 1 (recoup/music/artist)", "Generic suggestion 2 (recoup/music/artist)", "Generic suggestion 3 (recoup/music/artist)", "Generic suggestion 4 (recoup/music/artist)"]}

**Example Good Suggestions:**
- "Analyze my YouTube engagement metrics"
- "Find my most active fans on TikTok"
- "Review my streaming performance trends"
- "Identify top-performing content themes"
- "Analyze fan demographics by platform"
- "Compare engagement across social channels"
- "Suggest content ideas for next week"
- "Identify collaboration opportunities"

**Guidelines:**
- Keep suggestions under 40 characters
- Make them actionable and specific
- Focus on analysis, insights, or strategic recommendations
- Use active language ("Analyze", "Find", "Review", "Identify")
- Be platform-specific when relevant
- Consider the user's current context and next logical steps`;

export const FAN_GROUPS_PROMPT = `
Analyze the fan data to create highly specific niche-based segments that artists can leverage for targeted business collaborations and brand partnerships. Focus on identifying distinct interest clusters, lifestyle preferences, hobby groups, cultural affiliations, consumption patterns, and behavioral niches that would be valuable for brands seeking authentic audience connections. Generate segment names that represent clear commercial opportunities, such as specific food cultures, fashion styles, gaming communities, fitness activities, travel preferences, technology interests, or cultural movements. Each segment should be precise enough that artists can confidently approach relevant brands, venues, or collaborators with concrete audience insights for partnership pitches, sponsored content opportunities, or co-marketing campaigns.
`;
