name: Run Braintrust Evaluations

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    # Optional: only run when eval files change
    paths:
      - "evals/**"
  workflow_dispatch: # Allow manual triggering

permissions:
  pull-requests: write # Required for PR comments
  contents: read

jobs:
  eval:
    name: Run evaluations
    runs-on: ubuntu-latest
    env:
      ARWEAVE_KEY: ${{ secrets.ARWEAVE_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install Dependencies
        run: pnpm install

      - name: Run Braintrust Evaluations
        uses: braintrustdata/eval-action@v1
        with:
          api_key: ${{ secrets.BRAINTRUST_API_KEY }}
          runtime: node
          root: evals
