name: Run new evals

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  run_evals:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs
          git lfs install

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
          pip install supabase
          # Install the package with core dependencies first
          pip install -e .

      - name: Run get_premium_fans generator
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          echo "Running get_premium_fans registry data generator"
          python evals/scripts/get_premium_fans_generator.py

      - name: Get list of all YAML files in evals/registry/evals
        id: get_files
        run: |
          all_files=$(find evals/registry/evals -name "*.yaml")

          if [ -n "$all_files" ]; then
            # Replace newlines with commas to store in GitHub environment variable
            echo "all_files=${all_files//[$'\n']/,}" >> $GITHUB_ENV
          else
            echo "all_files=" >> $GITHUB_ENV 
          fi

      - name: Run oaieval command for each new YAML file
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          files="${{ env.all_files }}"
          if [ -n "$files" ]; then
            for file in $files; do
              echo "Processing $file"
              first_key=$(python .github/workflows/parse_yaml.py $file)
              echo "Eval Name: $first_key"
              oaieval gpt-3.5-turbo $first_key
            done
          else
            echo "No new YAML files found in evals/registry/evals"
          fi